### ISSUE TITLE
Error on Startup results in disabled ExtraGear

### ISSUE THREAD

**Issue by EchocallingEarth** [TheBusyBiscuit/ExtraGear#8]
Startup failure EXtraGear

![2020-02-13_12 43 27](https://user-images.githubusercontent.com/47970978/74462596-809ebb00-4e5e-11ea-8a62-74b79a0a333d.png)

https://pastebin.com/7btGTf31

**Comment by andris155** [comment]
```
[03:59:25] [Server thread/INFO]: [ExtraGear] Enabling ExtraGear vDEV - 5 (git e702d18d)
[03:59:25] [Server thread/ERROR]: Error occurred while enabling ExtraGear vDEV - 5 (git e702d18d) (Is it up to date?)
java.lang.IllegalArgumentException: Enchantment level is either too low or too high (given 8, bounds are 1 to 3)
	at org.bukkit.inventory.ItemStack.addEnchantment(ItemStack.java:395) ~[patched_1.15.2.jar:git-Paper-105]
	at io.github.thebusybiscuit.extragear.ExtraGear.registerSword(ExtraGear.java:197) ~[?:?]
	at io.github.thebusybiscuit.extragear.ExtraGear.onEnable(ExtraGear.java:74) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-105]
	at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.loadPlugins(NMSImpl.java:782) ~[?:?]
	at net.citizensnpcs.util.NMS.loadPlugins(NMS.java:294) ~[?:?]
	at net.citizensnpcs.Citizens.enableSubPlugins(Citizens.java:164) ~[?:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:323) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-105]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
